pc2[0]=B
pc2[image]=kathara/base

pc3[0]=C
pc3[image]=kathara/base

router1[0]=A
router1[1]=D
router1[2]=E
router1[image]=kathara/quagga

router2[0]=B
router2[1]=D
router2[2]=F
router2[image]=kathara/quagga

router3[0]=C
router3[1]=E
router3[2]=F
router3[image]=kathara/quagga

routerisp[0]=A
routerisp[image]=kathara/quagga
