webserver[0]=A
pc[0]=B
router1[0]=I
router1[1]=J
router1[image]=kathara/quagga
router2[0]=A
router2[1]=H
router2[2]=I
router2[image]=kathara/quagga
router3[0]=K
router3[1]=H
router3[image]=kathara/quagga
router4[0]=D
router4[1]=G
router4[2]=E
router4[image]=kathara/quagga
router5[0]=D
router5[1]=C
router5[image]=kathara/quagga
router6[0]=B
router6[1]=C
router6[2]=E
router6[3]=F
router6[image]=kathara/quagga
routerg[0]=F
routerg[1]=G
routerg[2]=J
routerg[image]=kathara/quagga
routerg[3]=K
