hostname ospfd
password zebra
enable password zebra

router ospf
 ospf router-id 6.6.6.6
 network 1.0.0.0/24 area 0.0.0.0
 network 10.0.56.0/28 area 0.0.0.0
 network 10.0.46.0/28 area 0.0.0.0
 network 10.0.60.0/28 area 0.0.0.0

log file /var/log/zebra/ospfd.log
