hostname ospfd
password zebra
enable password zebra

router ospf
 ospf router-id 10.10.10.10
 network 10.0.60.0/28 area 0.0.0.0
 network 10.0.40.0/28 area 0.0.0.0
 redistribute rip

log file /var/log/zebra/ospfd.log
